GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDExMjgyNjksImV4cCI6MTY0MTEzMTg2OSwiYXVkIjoiNjFiYTUxOGE2YTlhZTQzYmEyMWZjN2FiIiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.M4djop50nr38ztiUgr5DebvEDMjjJRlZWU_827NqXE4

###Login Route
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"miscadis@gmail.com",
    "password":"21372137"
}

###Register Route
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email":"miscadis@gmail.com",
    "password":"21372137"
}


###Refresh token Route
POST http://localhost:3000/auth/refresh-token

###Logout Route
DELETE  http://localhost:3000/auth/logout